### ISSUE TITLE
Developing real-time dashboard form layout 

### ISSUE THREAD

**Issue by Millennium-Heap** [Millennium-Heap/real-time-info-dashboard#1]
# Description
The initial phase of the project involves developing the base layout for our real-time dashboard info form which will include an angular gauge as well as a cartesian chart.

## Sub-Feature
- A user control for all the manipulation of our visuals in the form.
- An angular gauge to our form.
- An cartesian chart to our form.

## Dependencies
- LiveCharts.Wpf package

## Milestones
- [x] Add user control for all the manipulation of our visuals in the form.
- [x] Configure the user control form for column and row manipulations.
- [x] Add a start/stop button.
- [x] Develop an angular gauge for our form.
- [x] Develop an cartesian chart for our form.

# Member/Members (@Github-Handle) (@Email-Id)
- Millennium Singha (@Millennium-Heap) (millenniumsingha@gmail.com)
