### ISSUE TITLE
Data Binding

### ISSUE THREAD

**Issue by Millennium-Heap** [Millennium-Heap/real-time-info-dashboard#3]
# Description
In this phase, we shall develop the codebase to bind the provided data to us so as to display them in the angular gauge as well as in the cartesian chart.

## Sub-Feature
- A collection of values for our fictional manufacturing data.
- Start/Stop button functionality to read data from the source.
- Loaded and mapped data to the collection.

## Dependencies
- LiveCharts.wpf
- Developing real-time dashboard form layout #1

## Milestones
- [x] Adding a collection of values for the provided data.
- [x] Adding functionality to start/stop button to read data.
- [x] Load data into the collection
- [x] Map the data in the collection to the X and Y-axis in the chart.

## Member / Members (@Github-Handle) (@Email-Id)
- Millennium Singha (@Millennium-Heap) (millenniumsingha@gmail.com)
