### ISSUE TITLE
Multiple Line Series

### ISSUE THREAD

**Issue by Millennium-Heap** [Millennium-Heap/real-time-info-dashboard#9]
# Description
In this final phase, we shall develop the form layout for multiple line series and data-bind the necessary values to our respective line series so as to provide an efficient visual outlook/update of our fictional manufacturing data.

## Sub-Feature
- Add the multiple line series form layouts.
- Data-bind the values to the chart.
- Fine-tuned the visualization application.

## Examples (Optional)
![image](https://user-images.githubusercontent.com/78008633/107740277-be177c00-6d30-11eb-96fa-34449260cd08.png)

## Dependencies
- LiveCharts.Wpf
- Developing real-time dashboard form layout. #1 
- Data Binding. #3
- Formatting X-.Axis of the Cartesian Chart. #7

## Milestones
- [x] Develop the multiple line series for our form layouts.
- [x] Data-bind the values to the chart.
- [x] Fine-tune the visualization application.

## Member/Members (@Github-Handle) (@Email-Id)
- Millennium Singha (@Millennium-Heap) (millenniumsingha@gmail.com)
